from django.urls import path,re_path
from ..views import *

app_name = 'src'
urlpatterns = [
    path('dashboard', profile.index, name='dashboard'),
    path('dashboard-monthly-sale', profile.dashboardMonthly, name='dashboard-monthly-sale'),
    path('change-password', profile.changePassword, name='change-password'),
    path('organizations', organizations.index, name='organizations'),
    path('ajax-organization-list', organizations.ajaxOrganizationList, name='ajax-organization-list'),
    path('ajax-organization-lists', organizations.ajaxOrganizationLists, name='ajax-organization-lists'),
    path('add-organization', organizations.addOrganization, name='add-organization'),
    path('save-organization', organizations.saveOrganization, name='save-organization'),
    path('edit-organization', organizations.editOrganization, name='edit-organization'),
    path('update-organization', organizations.updateOrganization, name='update-organization'),
    path('get-organization-record', organizations.getOrganizationRecord, name='get-organization-record'),
    path('update-organization-status', organizations.updateOrganizationStatus, name='update-organization-status'),
    path('add-department', organizations.addDepartment, name='add-department'),
    path('save-department', organizations.saveDepartment, name='save-department'),
    path('edit-department', organizations.editDepartment, name='edit-department'),
    path('update-department', organizations.updateDepartment, name='update-department'),
    path('update-department-status', organizations.updateDepartmentStatus, name='update-department-status'),
    path('export-organizations-to-xlsx/<str:columns>', organizations.exportToXlsx, name='export-organizations-to-xlsx'),
    path('export-organizations-to-pdf/<str:columns>', organizations.exportToPDF, name="export-organizations-to-pdf"),
    
    path('roles', roleManagement.index, name='roles'),
    path('ajax-role-list', roleManagement.ajaxRoleList, name='ajax-role-list'),
    path('ajax-role-lists', roleManagement.ajaxRoleLists, name='ajax-role-lists'),
    path('add-role', roleManagement.addRole, name='add-role'),
    path('add-role-permission', roleManagement.addRolePermission, name='add-role-permission'),
    path('update-role-status', roleManagement.updateRoleStatus, name='update-role-status'),
    path('edit-role', roleManagement.editRole, name='edit-role'),

    path('permission-workflows', permissionWorkflow.index, name='permission-workflows'),
    path('update-permission-workflows', permissionWorkflow.updatePermissionWorkflows, name='update-permission-workflows'),
    path('update-permission-and-workflows', permissionWorkflow.updatePermissionAndWorkflows, name='update-permission-and-workflows'),
    path('remove-permission-and-workflows', permissionWorkflow.removePermissionAndWorkflows, name='remove-permission-and-workflows'),
    
    path('users', userManagement.index, name='users'),
    path('reset-user-credential/<str:user_id>', userManagement.resetCredential, name='reset-user-credential'),
    path('send-email', userManagement.sendEmail, name='send-email'),
    path('ajax-operational-users-list', userManagement.ajaxOperationalUsersList, name='ajax-operational-users-list'),
    path('ajax-non-operational-users-list', userManagement.ajaxNonOperationalUsersList, name='ajax-non-operational-users-list'),
    path('ajax-employee-users-list', userManagement.ajaxEmployeeUsersList, name='ajax-employee-users-list'),
    path('add-user-basic-detail', userManagement.addUserBasicDetail, name='add-user-basic-detail'),
    path('edit-user-basic-detail', userManagement.editUserBasicDetail, name='edit-user-basic-detail'),
    path('add-user-offical-detail', userManagement.addUserOfficalDetail, name='add-user-offical-detail'),
    path('edit-user-offical-detail', userManagement.editUserOfficalDetail, name='edit-user-offical-detail'),
    path('add-user-product-detail', userManagement.addUserProductDetail, name='add-user-product-detail'),
    path('update-user-variant-price', userManagement.updateUserVariantPrice, name='update-user-variant-price'),
    path('edit-user-product-detail', userManagement.editUserProductDetail, name='edit-user-product-detail'),
    path('add-user-document-detail', userManagement.addUserDocumentDetail, name='add-user-document-detail'),
    path('user-geo-tagged', userManagement.userGeoTagged, name='user-geo-tagged'),
    path('locate-users-on-map', userManagement.locateUsersOnMap, name='locate-users-on-map'),
    path('update-user-status', userManagement.updateUserStatus, name='update-user-status'),
    path('update-users-status', userManagement.updateUsersStatus, name='update-users-status'),
    path('update-user-product-status', userManagement.updateProductStatus, name='update-user-product-status'),
    path('export-operational-user-to-xlsx/<str:columns>/<str:Organisation>', userManagement.exportOperationalUserToXlsx, name='export-operational-user-to-xlsx'),
    path('export-operational-user-to-pdf/<str:columns>/<str:Organisation>', userManagement.exportOperationalUserToPdf, name='export-operational-user-to-pdf'),
    path('export-non-operational-user-to-xlsx/<str:columns>', userManagement.exportNonOperationalUserToXlsx, name='export-non-operational-user-to-xlsx'),
    path('export-non-operational-user-to-pdf/<str:columns>', userManagement.exportNonOperationalUserToPdf, name='export-non-operational-user-to-pdf'),
    path('export-employee-to-xlsx/<str:columns>', userManagement.exportEmployeeToXlsx, name='export-employee-to-xlsx'),
    path('export-employee-to-pdf/<str:columns>', userManagement.exportEmployeeToPdf, name='export-employee-to-pdf'),
    path('import-product-variant', userManagement.importProductVariant, name='import-product-variant'),

    path('add-employee-basic-detail', userManagement.addEmployeeBasicDetail, name='add-employee-basic-detail'),
    path('add-employee-official-detail', userManagement.addEmployeeOfficalDetail, name='add-employee-official-detail'),
    path('add-employee-attendance-detail', userManagement.addEmployeeAttendanceDetail, name='add-employee-attendance-detail'),
    path('add-employee-document-detail', userManagement.addEmployeeDocumentDetail, name='add-employee-document-detail'),

    path('edit-employee-basic-detail/<int:employee_id>', userManagement.editEmployeeBasicDetail, name='edit-employee-basic-detail'),
    path('edit-employee-official-detail/<int:employee_id>', userManagement.editEmployeeOfficalDetail, name='edit-employee-official-detail'),
    path('edit-employee-attendance-detail/<int:employee_id>', userManagement.editEmployeeAttendanceDetail, name='edit-employee-attendance-detail'),
    path('get-user-map', userManagement.getUserMap, name='get-user-map'),
    path('edit-employee-document-detail/<int:employee_id>', userManagement.editEmployeeDocumentDetail, name='edit-employee-document-detail'),

    path('user-short-details/<int:user_id>', userManagement.userShortDetail, name='user-short-details'),
    path('user-details/<int:user_id>', userManagement.userDetail, name='user-details'),
    path('get-user-order-details', userManagement.getOrderDetails, name='get-user-order-details'),
    path('employee-short-details/<int:employee_id>', userManagement.employeeShortDetail, name='employee-short-details'),
    path('employee-details/<int:employee_id>', userManagement.employeeDetail, name='employee-details'),

    path('user-tracking/<str:user_id>', userManagement.userTracking, name='user-tracking'),
    path('ajax-user-tracking/<str:user_id>', userManagement.ajaxUserTracking, name='ajax-user-tracking'),
    
    path('user-travel-summary', userManagement.userTravelSummary, name='user-travel-summary'),
    path('ajax-user-travel-summary-report', userManagement.ajaxuserTravelSummary, name='ajax-user-travel-summary-report'),
    path('get-travel-user-list', ajax.travelUserOption, name='get-travel-user-list'),
    path('export-user-travel-summary/<str:travel_date>/<str:user_id>/<str:travel_month_picker>/<str:time_period>', userManagement.exportUserTravelSummary, name='export-user-travel-summary'),

    path('view-user-role-permission/<int:user_id>', userManagement.viewUserRolePermission, name='view-user-role-permission'),
    path('update-user-role-permission', userManagement.updateUserRolePermission, name='update-user-role-permission'),
    path('check-role-permission', userManagement.checkRolePermision, name='check-role-permission'),
    path('save-role-permission-validity', userManagement.saveRolePermisionValidity, name='save-role-permission-validity'),
    
    path('user-tracking-report', userManagement.userTrackingReport, name='user-tracking-report'),
    path('get-report-user-list',ajax.orderReportUserList, name='get-report-user-list'),
    
    path('get-state-options/<int:country_id>', ajax.stateOption, name='get-state-options'),
    path('get-user-product-variant-list/<int:state_id>', ajax.cityOption, name='get-user-product-variant-list'),
    path('get-city-options/<int:state_id>', ajax.cityOption, name='get-city-options'),
    path('get-options-list', ajax.getOptionsList, name='get-options-list'),
   
    path('edit-role/<int:role_id>', roleManagement.editRole, name='edit-role'),
    path('role-details/<int:role_id>', roleManagement.roleDetails, name='role-details'),
    path('get-product-class/<str:largest_unit>', ajax.productClassOption, name='get-product-class'),
    path('get-user-product-variant-list', ajax.productOption, name='get-user-product-variant-list'),
    path('get-user-product-variant-details', ajax.productDetails, name='get-user-product-variant-details'),
    path('get-scheme-details', ajax.getSchemeDetails, name='get-scheme-details'),
    path('get-bonus-scheme-details', ajax.getBonusSchemeDetails, name='get-bonus-scheme-details'),
    path('get-product-free-scheme', ajax.getProductFreeScheme, name='get-product-free-scheme'),
    
    path('user-product-variant-list', ajax.getproductOption, name='user-product-variant-list'),
    path('user-product-variant-details',ajax.getproductDetails, name='user-product-variant-details'),


    path('get-state-towns/<int:state_id>', ajax.getStateTowns, name='get-state-towns'),
    path('get-zone-towns/<int:zone_id>', ajax.getZoneTowns, name='get-zone-towns'),
    path('get-route-towns/<int:route_id>', ajax.getRouteTowns, name='get-route-towns'),
    path('get-user-list', ajax.orderUserOption, name='get-user-list'),
    path('get-sap-route-list', ajax.sapRouteOption, name='get-sap-route-list'),
    path('get-vehicle-list', ajax.vehicleOptionList, name='get-vehicle-list'),

    path('check-towns-route-mapping/<int:town_id>', ajax.checkTownMappingRoute, name='check-towns-route-mapping'),
    
    path('update-favorite', ajax.updateFavorite, name='update-favorite'),
    path('get-add-role-permission/<int:role_id>', roleManagement.getAddRolePermission, name='get-add-role-permission'),
    path('get-org-department-options/<int:organization_id>', roleManagement.orgDepartmentOption, name='get-org-department-options'),
    path('get-org-role-options/<int:organization_id>', roleManagement.orgRoleOption, name='get-org-role-options'),
    path('get-department-role-options/<int:department_id>', roleManagement.departmentRoleOption, name='get-department-role-options'),
    path('get-grouped-town-options', userManagement.getGroupedTownOptions, name='get-grouped-town-options'),
    path('get-reporting-user-options/<int:role_id>', userManagement.getReportingUserOptions, name='get-reporting-user-options'),
    
    path('products', products.index, name='products'),
    path('ajax-product-list', products.ajaxProductList, name='ajax-product-list'),
    path('get-ordered-user-list',ajax.orderUserList, name='get-ordered-user-list'),
    # path('ajax-product-lists', products.ajaxProductLists, name='ajax-product-lists'),
    path('update-user-order-status', orders.updateUserOrderStatus, name='update-user-order-status'),
    path('add-product', products.addProduct, name='add-product'),
    path('save-product', products.saveProduct, name='save-product'),
    path('edit-product/<int:product_id>', products.editProduct, name='edit-product'),
    path('update-product-status', products.updateProductStatus, name='update-product-status'),
    path('get-product-variants/<int:product_id>', products.getProductVariants, name='get-product-variants'),
    path('ajax-product-variant-lists/<int:product_id>', products.ajaxProductVariantLists, name='ajax-product-variant-lists'),
    path('edit-product-variant/<int:product_variant_id>', products.editProductVariant, name='edit-product-variant'),
    path('add-product-variant/<int:product_id>', products.addProductVariant, name='add-product-variant'),
    path('product-unit-details/<int:unit_id>', products.productUnitDetails, name='product-unit-details'),
    path('update-product-variant-status', products.updateProductVariantStatus, name='update-product-variant-status'),

    path('schemes', scheme.index, name='schemes'),
    path('ajax-scheme-list', scheme.ajaxSchemeList, name='ajax-scheme-list'),
    path('add-free-scheme', scheme.addFreeScheme, name='add-free-scheme'),
    path('edit-free-scheme/<str:scheme_id>', scheme.editFreeScheme, name='edit-free-scheme'),
    path('add-bonus-scheme', scheme.addBonusScheme, name='add-bonus-scheme'),
    path('edit-bonus-scheme/<str:scheme_id>', scheme.editBonusScheme, name='edit-bonus-scheme'),
    path('add-flat-incentive-scheme', scheme.addFlatIncentiveScheme, name='add-flat-incentive-scheme'),
    path('edit-flat-incentive/<str:scheme_id>', scheme.editFlatIncentiveScheme, name='edit-flat-incentive'),
    path('add-bulkpack-incentive-scheme', scheme.addBulkpackIncentiveScheme, name='add-bulkpack-incentive-scheme'),
    path('edit-bulkpack-incentive/<str:scheme_id>', scheme.editBulkpackIncentiveScheme, name='edit-bulkpack-incentive'),
    path('get-filtered-users', scheme.getFilteredUsers, name='get-filtered-users'),
    path('get-incentive-filtered-users', scheme.getIncentiveFilteredUsers, name='get-incentive-filtered-users'),
    path('free-scheme-users/<int:scheme_id>', scheme.freeSchemeUsers, name='free-scheme-users'),
    path('latest-flat-incentive-users', scheme.latestFlatIncentiveUsers, name='latest-flat-incentive-users'),
    path('flat-incentive-users/<int:scheme_id>', scheme.flatIncentiveUsers, name='flat-incentive-users'),
    path('latest-bulkpack-incentive-users', scheme.latestBulkpackIncentiveUsers, name='latest-bulkpack-incentive-users'),
    path('bulkpack-incentive-users/<int:scheme_id>', scheme.bulkpackIncentiveUsers, name='bulkpack-incentive-users'),
    path('user-bulkpack-incentive-bifurcations/<str:user_id>/<str:scheme_id>', scheme.userBulkpackIncentiveBifurcations, name='user-bulkpack-incentive-bifurcations'),
    path('latest-quantitative-incentive-users', scheme.latestQuantitativeIncentiveUsers, name='latest-quantitative-incentive-users'),
    path('quantitative-incentive-users/<int:scheme_id>', scheme.quantitativeIncentiveUsers, name='quantitative-incentive-users'),
    path('user-quantitative-scheme-bifurcations/<str:user_id>/<str:scheme_id>', scheme.userQuantitativeSchemeBifurcations, name='user-quantitative-scheme-bifurcations'),
    path('update-free-scheme-status', scheme.updateFreeSchemeStatus, name='update-free-scheme-status'),
    path('update-quantitative-scheme-status', scheme.updateQuantitativeSchemeStatus, name='update-quantitative-scheme-status'),
    path('update-flat-incentive-status', scheme.updateFlatIncentiveSchemeStatus, name='update-flat-incentive-status'),
    path('update-bulkpack-incentive-status', scheme.updateBulkpackIncentiveSchemeStatus, name='update-bulkpack-incentive-status'),

    path('update-user-free-scheme-status', scheme.updateUserFreeSchemeStatus, name='update-user-free-scheme-status'),
    path('update-user-quantitative-scheme-status', scheme.updateUserQuantitativeSchemeStatus, name='update-user-quantitative-scheme-status'),
    path('update-user-flat-incentive-status', scheme.updateUserFlatIncentiveSchemeStatus, name='update-user-flat-incentive-status'),
    path('update-user-bulkpack-incentive-status', scheme.updateUserBulkpackIncentiveSchemeStatus, name='update-user-bulkpack-incentive-status'),

    path('get-state-route-options/<int:state_id>', ajax.stateRouteOptions, name='get-state-route-options'),
    path('get-route-town-options', ajax.routeTownOptions, name='get-route-town-options'),
    path('get-product-variant-details/<int:product_variant_id>', ajax.productVariantDetails, name='get-product-variant-details'),
    path('get-order-time', ajax.getOrderTime, name='get-order-time'),

    path('master-management', master.index, name='master-management'),

    path('get-zone-master-list', location.ajaxZoneList, name='get-zone-master-list'),
    path('get-town-master-list', location.ajaxTownList, name='get-town-master-list'),
    path('get-route-master-list', location.ajaxRouteList, name='get-route-master-list'),
    path('get-production-unit-list', location.ajaxProductionUnitList, name='get-production-unit-list'),

    path('add-zone', location.addZone, name='add-zone'),
    path('edit-zone/<str:zone_id>', location.editZone, name='edit-zone'),
    path('add-town', location.addTown, name='add-town'),
    path('edit-town/<str:town_id>', location.editTown, name='edit-town'),
    path('add-route', location.addRoute, name='add-route'),
    path('edit-route/<str:route_id>', location.editRoute, name='edit-route'),
    
    path('add-production-unit', location.addProductionUnit, name='add-production-unit'),
    path('edit-production-unit/<str:production_unit_id>', location.editProductionUnit, name='edit-production-unit'),
    path('update-production-unit-status', location.updateProductionUnitStatus, name='update-production-unit-status'),
    
    path('get-time-slot-master-list', location.ajaxTimeSlotList, name='get-time-slot-master-list'),
    path('edit-time-slot', location.editTimeSlot, name='edit-time-slot'),
    path('update-status', location.updateStatus, name='update-status'),
    
    path('get-main-route-master-list', location.ajaxMainRouteList, name='get-main-route-master-list'),
    path('add-main-route', location.addMainRoute, name='add-main-route'),
    path('edit-main-route/<str:route_id>', location.editMainRoute, name='edit-main-route'),
    path('get-sub-route/<int:route_id>', ajax.getMainSubRoute, name='get-sub-route'),
    path('get-sub-route-list', ajax.getMainSubRouteList, name='get-sub-route-list'),
    path('get-state-zone-list', ajax.getStateZoneList, name='get-state-zone-list'),
    path('get-zone-town-list', ajax.getZoneTownList, name='get-zone-town-list'),
    path('update-main-route-status', location.updateMainRoute, name='update-main-route-status'),
    path('update-route-status', location.updateRouteStatus, name='update-route-status'),
    
    path('get-packaging-type-master-list', location.ajaxPackagingTypeList, name='get-packaging-type-master-list'),
    path('add-packaging-type', location.addPackagingType, name='add-packaging-type'),
    path('edit-packaging-type/<str:id>', location.editPackagingType, name='edit-packaging-type'),
    path('update-packaging-type-status', location.updatePackagingTypeStatus, name='update-packaging-type-status'),
    
    path('get-containers-master-list', location.ajaxContainersList, name='get-containers-master-list'),
    path('add-containers', location.addContainers, name='add-containers'),
    path('edit-containers/<str:id>', location.editContainers, name='edit-containers'),
    path('update-containers-status', location.updateContainersStatus, name='update-containers-status'),
    
    path('get-product-class-master-list', location.ajaxProductClassList, name='get-product-class-master-list'),
    path('add-product-class', location.addProductClass, name='add-product-class'),
    path('edit-product-class/<str:id>', location.editProductClass, name='edit-product-class'),
    path('update-product-class-status', location.updateProductClassStatus, name='update-product-class-status'),
    
    path('get-incentive-slab-list', location.ajaxIncentiveSlabList, name='get-incentive-slab-list'),
    path('add-incentive-slab', location.addIncentiveSlab, name='add-incentive-slab'),
    path('edit-incentive-slab/<str:id>', location.editIncentiveSlab, name='edit-incentive-slab'),
    
    path('orders', orders.index, name='orders'),
    path('add-order', orders.addOrder, name='add-order'),
    path('save-order', orders.saveOrder, name='save-order'),
    path('get-defaulter-user-list', orders.getDefaulterUserList, name='get-defaulter-user-list'),
    path('orders/<int:order_status>', orders.searchOrder, name='orders'),
    path('ajax-orders-lists', orders.ajaxOrdersLists, name='ajax-orders-lists'),
    path('order-status-details', orders.orderStatusDetails, name='order-status-details'),
    path('get-order-details', orders.getOrderDetails, name='get-order-details'),
    path('edit-order', orders.editOrder, name='edit-order'),
    path('update-order', orders.updateOrder, name='update-order'),
    path('update-order-status', orders.updateOrderStatus, name='update-order-status'),
    path('indent-report', orders.indentReport, name='indent-report'),
    path('ajax-indent-report', orders.ajaxIndentReport, name='ajax-indent-report'),
    path('summary-report', orders.summaryReport, name='summary-report'),
    path('ajax-summary-report', orders.ajaxSummaryReport, name='ajax-summary-report'),
    path('packing-station-report', orders.packingStationReport, name='packing-station-report'),
    path('ajax-packing-station-report', orders.ajaxPackingStationReport, name='ajax-packing-station-report'),
    path('update-packing-station-report-refresh-time', orders.updatePackingStationReportRefreshTime, name='update-packing-station-report-refresh-time'),
    path('generate-indent-report', orders.generateIndentReport, name='generate-indent-report'),
    path('amount-to-be-paid-report', orders.amountToBePaidReport, name='amount-to-be-paid-report'),
    path('sales-report', orders.salesReport, name='sales-report'),
    path('ajax-sales-report-list',orders.ajaxSalesReportList, name='ajax-sales-report-list'),
    path('export-sales-report-list/<str:order_date>/<str:id>', orders.ajaxExportSaleReportList, name='export-sales-report-list'),
    path('ajax-amount-to-be-paid-report', orders.ajaxAmountToBePaidReport, name='ajax-amount-to-be-paid-report'),
    path('export-indent-report/<str:order_date>/<str:organization_id>', orders.exportIndentReport, name='export-indent-report'),
    path('export-summary-report/<str:order_date>', orders.exportSummaryReport, name='export-summary-report'),
    path('export-packing-station-report/<str:order_date>', orders.exportPackingStationReport, name='export-packing-station-report'),
    path('export-order-to-xlsx/<str:columns>/<int:town_id>/<int:route_id>/<str:user_sap_id>/<str:order_date>', orders.exportToXlsx, name='export-order-to-xlsx'),
    path('export-order-to-pdf/<str:columns>/<int:town_id>/<int:route_id>/<str:user_sap_id>/<str:order_date>', orders.exportToPDF, name='export-order-to-pdf'),
    path('export-amount-to-be-paid-report/<str:order_date>', orders.exportAmountToBePaidReport, name='export-amount-to-be-paid-report'),
    
    path('ho-report', orders.hoReport, name='ho-report'),
    path('update-ho-report', orders.updateHoReport, name='update-ho-report'),
    path('export-ho-report', orders.exportHoReport, name='export-ho-report'),
    
    path('truck-sheet-report', orders.truckSheetReport, name='truck-sheet-report'),
    
    path('trucksheet-dispatch-report', orders.truckSheetDispatchReport, name='trucksheet-dispatch-report'),
    path('ajax-trucksheet-dispatch-report', orders.ajaxTruckSheetDispatchReport, name='ajax-trucksheet-dispatch-report'),
    path('export-trucksheet-dispatch-report/<str:order_date>/<str:route_id>/<str:vehicle_id>', orders.exportTruckSheetDispatchReport, name='export-trucksheet-dispatch-report'),


    path('drivers', driver.index, name='drivers'),
    path('ajax-driver-list', driver.ajaxDriverList, name='ajax-driver-list'),
    path('add-driver', driver.addDriver, name='add-driver'),
    path('edit-driver-basic/<int:driver_id>', driver.editDriverBasic, name='edit-driver-basic'),
    path('edit-driver-official/<int:driver_id>', driver.editDriverOfficial, name='edit-driver-official'),
    path('driver-short-details/<int:driver_id>', driver.driverShortDetails, name='driver-short-details'),
    path('driver-details/<int:driver_id>', driver.driverDetails, name='driver-details'),
    path('update-driver-status', driver.updateDriverStatus, name='update-driver-status'),

    path('vehicles', vehicle.index, name='vehicles'),
    path('ajax-vehicle-list', vehicle.ajaxVehicleList, name='ajax-vehicle-list'),
    path('add-vehicle-basic', vehicle.addVehicleBasic, name='add-vehicle-basic'),
    path('edit-vehicle-basic/<str:vehicle_id>', vehicle.editVehicleBasic, name='edit-vehicle-basic'),
    path('edit-vehicle-registration/<str:vehicle_id>', vehicle.editVehicleRegistration, name='edit-vehicle-registration'),
    path('edit-vehicle-other/<str:vehicle_id>', vehicle.editVehicleOther, name='edit-vehicle-other'),
    path('edit-vehicle-route/<str:vehicle_id>', vehicle.editVehicleRoute, name='edit-vehicle-route'),
    path('edit-vehicle-credential/<str:vehicle_id>', vehicle.editVehicleCredential, name='edit-vehicle-credential'),
    path('update-vehicle-status', vehicle.updateVehicleStatus, name='update-vehicle-status'),
    path('vehicle-short-details/<str:vehicle_id>', vehicle.vehicleShortDetails, name='vehicle-short-details'),

    path('vehicle-registration-list/<str:vehicle_id>', vehicle.ajaxRegistrationList, name='vehicle-registration-list'),
    path('add-pollutionDetails/<str:vehicle_id>', vehicle.addPollutionDetails, name='add-pollutionDetails'),
    path('edit-pollutionDetails/<str:pollution_id>', vehicle.editPollutionDetails, name='edit-pollutionDetails'),
    path('add-RegistrationDetails/<str:vehicle_id>', vehicle.addRegistrationDetails, name='add-RegistrationDetails'),
    path('edit-RegistrationDetails/<str:registration_id>', vehicle.editRegistrationDetails, name='edit-RegistrationDetails'),
    path('add-FitnessDetails/<str:vehicle_id>', vehicle.addFitnessDetails, name='add-FitnessDetails'),
    path('edit-FitnessDetails/<str:fitness_id>', vehicle.editFitnesDetails, name='edit-FitnessDetails'),
    path('add-InsuranceDetails/<str:vehicle_id>', vehicle.addInsuranceDetails, name='add-InsuranceDetails'),
    path('edit-InsuranceDetails/<str:insurance_id>', vehicle.editInsuranceDetails, name='edit-InsuranceDetails'),
    path('add-PermitDetails/<str:vehicle_id>', vehicle.addPermitDetails, name='add-PermitDetails'),
    path('edit-PermitDetails/<str:permit_id>', vehicle.editPermitDetails, name='edit-PermitDetails'),

    path('grievances', grievance.index, name='grievances'),
    path('ajax-grievance-list', grievance.ajaxGrievanceList, name='ajax-grievance-list'),
    path('grievance-short-details/<str:grievance_id>', grievance.grievanceDetails, name='grievance-short-details'),
    path('export-grievance-to-xlsx/<str:columns>', grievance.exportGrievanceToXls, name='export-grievance-to-xlsx'),
    path('export-grievance-to-pdf/<str:columns>', grievance.exportGrievanceToPDF, name='export-grievance-to-pdf'),
    
    path('export-outstanding-template', scheme.exportOutstandingExcel, name='export-outstanding-template'),
    path('upload-outstanding', scheme.importOutstanding, name='upload-outstanding'),
    path('update-outstanding', scheme.updateOutstanding, name='update-outstanding'),

    path('export-scheme-template', scheme.exportSchemeExcel, name='export-scheme-template'),
    path('upload-scheme', scheme.importScheme, name='upload-scheme'),
    path('update-scheme', scheme.updateScheme, name='update-scheme'),

    path('export-rate-list-template', scheme.exportRateListExcel, name='export-rate-list-template'),
    path('upload-rate-list', scheme.importRateList, name='upload-rate-list'),
    path('update-rate-list', scheme.updateRateList, name='update-rate-list'),
    
    path('export-revised-template', scheme.exportRevisedExcel, name='export-revised-template'),
    path('upload-revised-amount', scheme.importRevisedAmount, name='upload-revised-amount'),
    path('update-revised-amount', scheme.updateRevisedAmount, name='update-revised-amount'),
    
    path('print-all', accounts.printAll, name='print-all'),
    path('invoice-list', accounts.invoiceList, name='invoice-list'),
    path('ajax-invoice-list', accounts.ajaxInvoiceList, name='ajax-invoice-list'),
    path('print-invoice/<str:order_date>/<str:invoice_id>', accounts.printInvoice, name='print-invoice'),
    path('print-invoice-template/<str:order_date>/<str:invoice_id>', accounts.printInvoiceTemplate, name='print-invoice-template'),
    path('print-all-invoice-template',accounts.printAllInvoiceTemplate, name='print-all-invoice-template'),
    path('single-user-all-download/<str:start_date>/<str:end_date>/<str:id>/<str:organization>',accounts.singleUserAllDownload,name='single-user-all-download'),
    
    path('genrate-invoice-template', accounts.genrateInvoiceTemplate, name='genrate-invoice-template'),  
    path('challan',accounts.gatePassAndChallan,name='challan'),
    path('ajax-challan',accounts.ajexGatePassAndChallan,name='ajax-challan'),
    path('print-challan-template', accounts.printGatepassAndChallan, name='print-challan-template'),
    path('print-all-challan-template', accounts.printAllGatepassAndChallan, name='print-all-challan-template'),
    
    path('customer-ledger',accounts.customerLedger,name='customer-ledger'),
    path('ajax-user-ledger',accounts.ajaxCustomerLedger,name='ajax-user-ledger'),
    
    path('attendance-report', report.attendanceReport, name='attendance-report'),
    path('ajax-attendance-report', report.ajaxAttendanceReport, name='ajax-attendance-report'),
    
    path('employee-report', report.employeeReport, name='employee-report'),
    path('ajax-employee-report', report.ajaxEmployeeReport, name='ajax-employee-report'),
    path('export-employee-report-to-xlsx/<str:columns>/<str:search_date>', report.exportEmployeeReport, name='export-employee-report-to-xlsx'),
    
    
    path('foc-requests', orders.focRequests, name='foc-requests'),
    path('foc-requests-details/<str:foc_request_id>', orders.FocRequestDetails, name='foc-requests-details'),
    path('ajax-foc-requests-lists', orders.ajaxFocRequestList, name='ajax-foc-requests-lists'),
    path('foc-record-by-date-name', orders.FocRecordByDateName, name='foc-record-by-date-name'),
    path('users-for-foc-record', orders.usersForFoc, name='users-for-foc-record'),
    path('foc-status-details', orders.focStatusDetails, name='foc-status-details'),
    path('update-foc-status', orders.updateFocStatus, name='update-foc-status'),
    path('export-foc-report-to-xlsx/<str:columns>/<str:userName>/<str:states>/<str:delvry_time>', orders.focExportToXlsx, name='export-foc-report-to-xlsx'),
    path('export-foc-report-to-pdf/<str:columns>/<str:userName>/<str:states>/<str:delvry_time>', orders.focExportToPDF, name='export-foc-report-to-pdf'),

    path('leave-report', report.leaveReport, name='leave-report'),
    path('ajax-leave-report-lists', report.ajaxLeaveReportLists, name='ajax-leave-report-lists'),
    path('edit-leave-status', report.editLeaveStatus, name='edit-leave-status'),
    path('leave-status-details', report.leaveStatusDetails, name='leave-status-details'),
    path('update-leave-status', report.updateLeaveStatus, name='update-leave-status'),
    path('update-leave-remark', report.updateLeaveRemark, name='update-leave-remark'),
    path('export-leave-report-to-xlsx/<str:columns>/<str:userId>/<str:leave_status>', report.leaveExportToXlsx, name='export-leave-report-to-xlsx'),
    path('export-leave-report-to-pdf/<str:columns>/<str:userId>/<str:leave_status>', report.leaveExportToPDF, name='export-leave-report-to-pdf'),
    
    path('bulk-notifications', notification.index, name='bulk-notifications'),
    path('ajax-notification-report', notification.ajaxNotificationReport, name='ajax-notification-report'),
    path('export-notification-report-to-xlsx/<str:columns>/<str:filter_notification_type>/<str:role>/<str:from_date>/<str:to_date>/<str:keyword>', notification.exportNotificationReport, name='export-notification-report-to-xlsx'),
    path('notification/get-users-option', notification.getUsersOptions, name='notification/get-users-option'),
    path('notification/get-route-towns-options', notification.getRouteTownsOptions, name='notification/get-route-towns-options'),
    path('notification/get-details/<str:notification_id>', notification.getNotificationDetails, name='notification/get-details'),
    path('send-notification', notification.sendNotification, name='send-notification'),
    
    path('crate-summary', crates.index, name='crate-summary'),
    path('manage-crate', crates.addCrate, name='manage-crate'),
    path('get-user-crate-detail',ajax.getUserCrateDetail, name='get-user-crate-detail'),
    path('get-user-recive-crate-detail',ajax.getUserReciveCrateDetail, name='get-user-recive-crate-detail'),
    # path('save-crate', crates.saveCrates, name='save-crate'),
    path('save-crate', crates.saveCreatesDetails, name='save-crate'),
    path('ajax-crate-summary', crates.ajaxCrateSummary, name='ajax-crate-summary'),
    path('export-crate-summary/<str:crate_date>/<str:crate_type>/<str:route_id>', crates.exportCrateSummary, name='export-crate-summary'),

    path('user-crate-summary', crates.userCrateSummary, name='user-crate-summary'),
    path('ajax-user-crate-summary', crates.ajaxUserCrateSummary, name='ajax-user-crate-summary'),
    path('export-user-crate-summary/<str:crate_date>/<str:crate_type>/<str:user_id>', crates.exportUserCrateSummary, name='export-user-crate-summary'),
    
    path('user-crate-report', crates.userCrateReport, name='user-crate-report'),
    path('ajax-user-crate-report', crates.ajaxUserCrateReport, name='ajax-user-crate-report'),
    path('export-user-crate-report/<str:crate_date>/<str:user_id>', crates.exportUserCrateReport, name='export-user-crate-report'),

    path('monthly-crate-report', crates.userMonthlyCrateReport, name='monthly-crate-report'),
    path('ajax-monthly-crate-report', crates.ajaxUserMonthlyCrateReport, name='ajax-monthly-crate-report'),
    path('export-user-monthly-crate-report/<str:crate_date>/<str:user_id>', crates.exportUserMonthlyCrateReport, name='export-user-monthly-crate-report'),


    path('holidays', holiday.index, name='holidays'),
    path('add-holiday', holiday.addHoliday, name='add-holiday'),
    path('edit-holiday/<str:holiday_id>', holiday.editHoliday, name='edit-holiday'),
    path('holidays/holiday-calendar/<str:holiday_id>', holiday.holidayCalendar, name='holidays/holiday-calendar'),
    path('holidays/filter-holiday/<str:filter_status>', holiday.filterHoliday, name='holidays/filter-holiday'),
    path('update-holiday-status', holiday.updateHolidayStatus, name='update-holiday-status'),
    path('export-holidays-to-xlsx/<str:filter_status>', holiday.exportToXlsx, name="export-holidays-to-xlsx"),
    path('export-holidays-to-pdf/<str:filter_status>', holiday.exportToPDF, name="export-holidays-to-pdf"),

    path('sales-plan', salesPlan.index, name='sales-plan'),
    path('add-sales-plan', salesPlan.addSalesPlan, name='add-sales-plan'),
    path('sales-plan/add/render-interval-view/<str:interval>', salesPlan.renderIntervalAddView, name='sales-plan/add/render-interval-view'),
    path('update-sales-plan-status', salesPlan.updateSalesPlanStatus, name='update-sales-plan-status'),
    path('edit-sales-plan/<int:sales_plan_id>', salesPlan.editSalesPlan, name='edit-sales-plan'),
    
    path('create-incentive', userManagement.createIncentive, name='create-incentive'),
    
    path('generate-incentive', userManagement.generateIncentive, name='generate-incentive'),
    
    path('incentive-report', report.incentiveReport, name='incentive-report'),
    path('ajax-incentive-report', report.ajaxIncentiveReport, name='ajax-incentive-report'),
    path('export-incentive-report/<str:search_date>/<str:fortnight>', report.exportIncentiveReport, name='export-incentive-report'),

    path('get-options-vehicle-list', ajax.getOptionsVehicleList, name='get-options-vehicle-list'),
    
    path('export-order-template', scheme.exportOrderExcel, name='export-order-template'),
    path('upload-order-list', scheme.importOrderList, name='upload-order-list'),
    path('update-order-list', scheme.updateOrderList, name='update-order-list'),
    #----------------------------for account ledger-------------------------
    path('credit-user-ledger', accounts.addCreditLedger, name='credit-user-ledger'),
    path('save-credit-ledger', accounts.saveCreditLedger, name='save-credit-ledger'),
    path('get-organization-to-users',ajax.getOrganizationTousers, name='get-organization-to-users'),
    path('get-bank', ajax.getBank, name='get-bank'),
    
    path('get-banks', location.ajaxBanks, name='get-banks'),
    path('add-bank-details', location.addBankDetails, name='add-bank-details'),
    path('update-bank-status', location.updateBankStatus,name='update-bank-status'),
    path('edit-bank-details/<str:bank_id>',location.editBankDetails, name='edit-bank-details'),
    
    path('save-credit-debit-note', accounts.saveCreditDebitNote, name='save-credit-debit-note'),
    # -----------------------------------------------------
    path('update-user-variant-limit', userManagement.updateUserVariantLimit, name='update-user-variant-limit'),
    # -----------------------------------------------
    #for tcs master
    path('get-tcs-list', master.ajaxtcs, name='get-tcs-list'),
    path('add-tcs', master.addTcs, name='add-tcs'),
    path('edit-tcs/<str:id>', master.editTcs, name='edit-tcs'),
    
    #for update ledger
    path('edit-customer-ledger',accounts.editcustomerLedger,name='edit-customer-ledger'),
    path('ajax-edit-user-ledger',accounts.ajaxeditCustomerLedger,name='ajax-edit-user-ledger'),
    path('update-ledger', accounts.updateLedger, name='update-ledger'),
    path('ajax-user-bank', accounts.getuserbank, name='ajax-user-bank'),
    path('clear-device-id', userManagement.clearDeviceId, name='clear-device-id'),


]